/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DeTodoS;

public class VentanaPrincipal1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal1.class.getName());
    private ProductoRepositorio repositorio;

    /**
     * Creates new form A
     */
    public VentanaPrincipal1() {
        initComponents();
        repositorio = new ProductoRepositorio(new java.util.TreeSet<>());
    }
  
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jDPVentanaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMAdministracion = new javax.swing.JMenu();
        jMIGestionarProductos = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMIConsultarPorNombre = new javax.swing.JMenuItem();
        jMIConsultarPorPrecio = new javax.swing.JMenuItem();
        jMIConsultarPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("De Todo S.A.");

        javax.swing.GroupLayout jDPVentanaPrincipalLayout = new javax.swing.GroupLayout(jDPVentanaPrincipal);
        jDPVentanaPrincipal.setLayout(jDPVentanaPrincipalLayout);
        jDPVentanaPrincipalLayout.setHorizontalGroup(
            jDPVentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jDPVentanaPrincipalLayout.setVerticalGroup(
            jDPVentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jMAdministracion.setText("Administracion");

        jMIGestionarProductos.setText("Gestionar Productos");
        jMIGestionarProductos.addActionListener(this::jMIGestionarProductosActionPerformed);
        jMAdministracion.add(jMIGestionarProductos);

        jMenuBar2.add(jMAdministracion);

        jMConsultas.setText("Consultas");

        jMIConsultarPorNombre.setText("Consultar Por Nombre");
        jMConsultas.add(jMIConsultarPorNombre);

        jMIConsultarPorPrecio.setText("Consultar Por Precio");
        jMConsultas.add(jMIConsultarPorPrecio);

        jMIConsultarPorRubro.setText("Consultar Por Rubo");
        jMConsultas.add(jMIConsultarPorRubro);

        jMenuBar2.add(jMConsultas);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDPVentanaPrincipal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPVentanaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGestionarProductosActionPerformed
        GestionDeProductos ventana = new GestionDeProductos(repositorio);
        jDPVentanaPrincipal.add(ventana);
        ventana.setVisible(true);
        try {
            ventana.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIGestionarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPVentanaPrincipal;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMIConsultarPorNombre;
    private javax.swing.JMenuItem jMIConsultarPorPrecio;
    private javax.swing.JMenuItem jMIConsultarPorRubro;
    private javax.swing.JMenuItem jMIGestionarProductos;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
