/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DeTodoS;


public class GestionDeProductos extends javax.swing.JInternalFrame {

    private javax.swing.table.DefaultTableModel modeloProductos;
    private ProductoRepositorio repositorio;

    /**
     * Creates new form GestionDeProductos
     */
    public GestionDeProductos(ProductoRepositorio repositorio) {
        initComponents();
        this.repositorio = repositorio;

        modeloProductos = new javax.swing.table.DefaultTableModel(
                new Object[]{"Codigo", "Descripcion", "Precio", "Categoria", "Stock"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTGestordeProductos.setModel(modeloProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTGestordeProductos = new javax.swing.JTable();
        jLCodigo = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jLDescripcion = new javax.swing.JLabel();
        jTDescripcion = new javax.swing.JTextField();
        jLPrecio = new javax.swing.JLabel();
        jTPrecio = new javax.swing.JTextField();
        jLCategoria = new javax.swing.JLabel();
        jCBCategoria = new javax.swing.JComboBox<>();
        jLStock = new javax.swing.JLabel();
        jSpStock = new javax.swing.JSpinner();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();

        setTitle("Gestion de Productos");

        jTGestordeProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Categoria", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTGestordeProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTGestordeProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTGestordeProductos);

        jLCodigo.setText("Codigo");

        jLDescripcion.setText("Descripcion");

        jLPrecio.setText("Precio");

        jLCategoria.setText("Categoria");

        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comestible", "Limpieza", "Perfumeria", " " }));
        jCBCategoria.addActionListener(this::jCBCategoriaActionPerformed);

        jLStock.setText("Stock");

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(this::jBNuevoActionPerformed);

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(this::jBGuardarActionPerformed);

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(this::jBActualizarActionPerformed);

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(this::jBEliminarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCodigo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDescripcion)
                            .addComponent(jLPrecio)
                            .addComponent(jLCategoria)
                            .addComponent(jLStock))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDescripcion)
                            .addComponent(jTPrecio)
                            .addComponent(jCBCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpStock)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCodigo)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrecio)
                    .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCategoria)
                    .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStock)
                    .addComponent(jSpStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCategoriaActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        jTCodigo.setText("");
        jTCodigo.setEnabled(true);
        jTDescripcion.setText("");
        jTPrecio.setText("");
        jSpStock.setValue(0);
        jTDescripcion.setEnabled(true);
        jTPrecio.setEnabled(true);
        jCBCategoria.setEnabled(true);
        jSpStock.setEnabled(true);
        jBGuardar.setEnabled(true);
        jBActualizar.setEnabled(false);
        jBEliminar.setEnabled(false);
        jTCodigo.requestFocus();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        String descripcion = jTDescripcion.getText().trim();
        String precioTexto = jTPrecio.getText().trim();
        String categoriaTexto = (String) jCBCategoria.getSelectedItem();
        int stock = (int) jSpStock.getValue();

        if (descripcion.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La descripción no puede estar vacía.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (precioTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio no puede estar vacío.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double precio;
        try {
            precio = Double.parseDouble(precioTexto.replace(",", "."));
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio ingresado no es un número válido.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (precio <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio debe ser mayor a cero.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Rubro rubro;
        try {
            rubro = Rubro.valueOf(categoriaTexto.trim().toUpperCase());
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Seleccioná una categoría válida.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo = repositorio.listarTodos().size() + 1;

        Producto producto = new Producto(codigo, descripcion, precio, stock, rubro);
        repositorio.agregar(producto);

        refrescarTabla();

        jTCodigo.setText("");
        jTDescripcion.setText("");
        jTPrecio.setText("");
        jSpStock.setValue(0);
        jTDescripcion.requestFocus();

    }//GEN-LAST:event_jBGuardarActionPerformed
    private void refrescarTabla() {
        modeloProductos.setRowCount(0); // borra todas las filas actuales
        for (Producto p : repositorio.listarTodos()) {
            modeloProductos.addRow(new Object[]{
                p.getCodigo(), p.getDescripcion(), p.getPrecio(), p.getRubro(), p.getStock()
            });
        }
    }
    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        String descripcion = jTDescripcion.getText().trim();
        String precioTexto = jTPrecio.getText().trim();
        String categoriaTexto = (String) jCBCategoria.getSelectedItem();
        int stock = (int) jSpStock.getValue();
        int codigo = Integer.parseInt(jTCodigo.getText().trim());

        if (descripcion.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La descripción no puede estar vacía.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (precioTexto.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio no puede estar vacío.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double precio;
        try {
            precio = Double.parseDouble(precioTexto.replace(",", "."));
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio ingresado no es un número válido.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (precio <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El precio debe ser mayor a cero.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Rubro rubro;
        try {
            rubro = Rubro.valueOf(categoriaTexto.trim().toUpperCase());
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Seleccioná una categoría válida.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Producto productoActualizado = new Producto(codigo, descripcion, precio, stock, rubro);
        repositorio.actualizar(codigo, productoActualizado);

        refrescarTabla();

        jTCodigo.setText("");
        jTDescripcion.setText("");
        jTPrecio.setText("");
        jSpStock.setValue(0);

        jTCodigo.setEnabled(true);
        jTDescripcion.setEnabled(false);
        jTPrecio.setEnabled(false);
        jCBCategoria.setEnabled(false);
        jSpStock.setEnabled(false);

        jBGuardar.setEnabled(false);
        jBActualizar.setEnabled(false);
        jBEliminar.setEnabled(false);
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jTGestordeProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTGestordeProductosMouseClicked
        int filaSeleccionada = jTGestordeProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            return; // no hay ninguna fila seleccionada, no hacemos nada
        }
        int codigo = (int) modeloProductos.getValueAt(filaSeleccionada, 0);
        String descripcion = (String) modeloProductos.getValueAt(filaSeleccionada, 1);
        double precio = (double) modeloProductos.getValueAt(filaSeleccionada, 2);
        Rubro rubro = (Rubro) modeloProductos.getValueAt(filaSeleccionada, 3);
        int stock = (int) modeloProductos.getValueAt(filaSeleccionada, 4);
        jTCodigo.setText(String.valueOf(codigo));
        jTDescripcion.setText(descripcion);
        jTPrecio.setText(String.valueOf(precio));
        jCBCategoria.setSelectedItem(capitalizar(rubro.toString()));
        jSpStock.setValue(stock);
        jTCodigo.setEnabled(false); // el código no se debería poder editar
        jBGuardar.setEnabled(false);
        jBActualizar.setEnabled(true);
        jBEliminar.setEnabled(true);
    }//GEN-LAST:event_jTGestordeProductosMouseClicked

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        int filaSeleccionada = jTGestordeProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Seleccioná un producto de la tabla para eliminar.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int codigo = (int) modeloProductos.getValueAt(filaSeleccionada, 0);
        String descripcion = (String) modeloProductos.getValueAt(filaSeleccionada, 1);

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Seguro que querés eliminar el producto \"" + descripcion + "\"?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return; // el usuario canceló
        }
        repositorio.eliminar(codigo);
        refrescarTabla();
        jTCodigo.setText("");
        jTDescripcion.setText("");
        jTPrecio.setText("");
        jSpStock.setValue(0);
        jTCodigo.setEnabled(true);
        jTDescripcion.setEnabled(false);
        jTPrecio.setEnabled(false);
        jCBCategoria.setEnabled(false);
        jSpStock.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBActualizar.setEnabled(false);
        jBEliminar.setEnabled(false);
    }//GEN-LAST:event_jBEliminarActionPerformed
    private String capitalizar(String texto) {
        return texto.substring(0, 1).toUpperCase() + texto.substring(1).toLowerCase();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JLabel jLCategoria;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLPrecio;
    private javax.swing.JLabel jLStock;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpStock;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTable jTGestordeProductos;
    private javax.swing.JTextField jTPrecio;
    // End of variables declaration//GEN-END:variables
}
